### ISSUE TITLE
【BUG?】Spring1  Spring2 链报错 ClassNotFoundException

### ISSUE THREAD

**Issue by winezer0** [Y4er/ysoserial#9]
java -jar ysoserial-latest.jar Spring1 calc
Error while generating or serializing payload
java.lang.ClassNotFoundException: org.springframework.core.SerializableTypeWrapper$TypeProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at ysoserial.payloads.Spring1.getObject(Spring1.java:74)
        at ysoserial.GeneratePayload.main(GeneratePayload.java:34)

**Comment by winezer0** [comment]
java -jar ysoserial-latest.jar Spring2 calc
Error while generating or serializing payload
java.lang.ClassNotFoundException: org.springframework.core.SerializableTypeWrapper$TypeProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at ysoserial.payloads.Spring2.getObject(Spring2.java:66)
